# Site Settings
lang: es
title: Bulma Clean Theme
tagline: MCD-UNISON
email: lu.fernando2901@gmail.com
description: Página del proyecto final del curso Ingeniería de Características de la maestría en Ciencia de Datos, que describe el proceso de obtener, limpieza y 
visualización de la información sobre las defunciones por diabetes en el Estado de Sonora
baseurl: "/"
url: "https://Fernando-LunaP/diabetes-en-sonora"
permalink: pretty

footer_menu: footer


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -

markdown: kramdown
highlighter: rouge
