remote_theme: chrisrhymes/bulma-clean-theme

# Site Settings
lang: es
title: Diabetes en Sonora
tagline: MCD-UNISON
email: lu.fernando2901@gmail.com
description: Página del proyecto final del curso Ingeniería de Características de la maestría en Ciencia de Datos, que describe el proceso de obtener, limpieza y visualización de la información sobre las defunciones por diabetes en el Estado de Sonora
baseurl: "/"
url: "https://Fernando-LunaP/diabetes-en-sonora"
permalink: pretty
favicon: https://github.com/Maleniski/ing-caracteristicas-migrantes-sonora-arizona/raw/main/docs/imagenes/favicon.ico


footer_menu: footer


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -

markdown: kramdown
highlighter: rouge
